### ISSUE TITLE
Improve .gitignore functions

### ISSUE THREAD

**Issue by EricCrosson** [egg-shell/instigitr#11]
- [x] handle gitignore choice more elegantly
  - Currently, instigitr relies on the user to get the type of their repo correct (as in, it matches with the case exactly in the github/gitignore list).
- [x] allow multiple github/gitignore choices
  - e.g. [C++](https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore) and [Qt](https://github.com/github/gitignore/blob/master/Qt.gitignore)
  - via @EricCrosson: 
    
    > Combining this with #11 makes me think of an auto-complete framework with multi-candidate selection, e.g. helm in emacs

**Comment by eggshell** [comment]
973f247e57dca40a718e152d00742095bdf4cf31 addresses the first part of this issue.

**Comment by eggshell** [comment]
2f6d3ed51129f8e12fc319dcb186d5f569342bea addresses the second bullet point.
